server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enable: true
  redis-mapper:
    host: 127.0.0.1:6379
markerhub:
  jwt:
    # 加密密钥
    secret: abcdefg1234567
    # token 有效时常 单位：s
    expire: 604800
    header: Authorization
